-- AlterTable
ALTER TABLE "Pod" ADD COLUMN IF NOT EXISTS "tagline" TEXT;
ALTER TABLE "Pod" ADD COLUMN IF NOT EXISTS "contactEmail" TEXT;
ALTER TABLE "Pod" ADD COLUMN IF NOT EXISTS "websiteUrl" TEXT;
ALTER TABLE "Pod" ADD COLUMN IF NOT EXISTS "instagramUrl" TEXT;
ALTER TABLE "Pod" ADD COLUMN IF NOT EXISTS "pickupInstructions" TEXT;
ALTER TABLE "Pod" ADD COLUMN IF NOT EXISTS "amenities" JSONB;
