-- AlterTable
ALTER TABLE "Pod" ADD COLUMN IF NOT EXISTS "accentColor" TEXT;

-- AlterTable
ALTER TABLE "PodVendor" ADD COLUMN IF NOT EXISTS "isFeatured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "PodVendor" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;